on:
 workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Dev   # Test environment

    steps:
      - run: echo "Deploying to staging" 
      - name: Start Timer
        uses: JesperDramsch/action-timer@v1
        with:
          action: start

