name: testing
on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:
      
  
jobs:
  job1:
   runs-on: ubuntu-latest
   environment: production
   strategy:
     matrix:
       node:
        - 14
        - 16
        - 18
   steps:
    - name: checkout the code
      uses: actions/checkout@v4
    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-versions: ${{matrix.node}}
    - name: print env secrets
      run: echo $API_PROD_ENV
      env:
        API_PROD_ENV: ${{secrets.API_PROD_ENV}}
       
     
    
  
    
    
